version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "kdev"
    commit-message:
        prefix: "⬆️"
        include: "scope"
    reviewers:
      - "kdev"
    target-branch: "dev"
